apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-kubernetes-component
  annotations:
    jenkins.io/job-full-name: folder/multibranchtest  
    backstage.io/kubernetes-id: my-kubernetes-component
    github.com/project-slug: gowthamshankar99/jenkinstest
spec:
  lifecycle: production
  owner: my-team
  type: service
